### ISSUE TITLE
zabbix template template_net_memory

### ISSUE THREAD

**Issue by androponia** [jpastuszek/zabbix-templates#1]
Hi, i have import your template of .net memory because is what i was looking for, but it doesnt work for me:

Cannot obtain performance information from collector.

I have a Zabbix server 2.4 , do you know if some variables change?

Thnaks a lot!

**Comment by jpastuszek** [comment]
Hi, I have updated it (just some tweaks).

You need to set macro on your host `{$NET_APP_NAME}`.
The value for it should be your process name for example `EmailService` or `w3wp` for IIS (with one worker process). You need to check `perfmon` application to find correct value for the process you want to monitor (look for `\.NET CLR Memory(<this value>)`). Also you can run `typeperf -qx` in command line to obtain all available performance counters on your Windows server and look there

The export is from Zabbix 2.2.2 but should be OK with your version I believe.

**Comment by androponia** [comment]
Thanks so much! it works!
